### ISSUE TITLE
Next question arrow covered by progress bar

### ISSUE THREAD

**Issue by 4of92000** [HodofHod/Userscripts#5]
Since the lesson update where you don't have x lives, but rather you have to do extra questions to finish the lesson, the next question button has been covered by the lesson progress bar, so it's hard (though not impossible) to hit. Could you fix that, please? Thanks.

**Comment by eagleeyez** [comment]
I did fix it in my fork please check and install it from there

**Comment by eagleeyez** [comment]
https://github.com/eagleeyez/Userscripts

Select the Mod it will install all the scripts from my fork and I fixed almost all the issues that I've found since Duolingo latest updates... I guess you know how to install it from RAW

**Comment by HodofHod** [comment]
This issue has now been fixed with f9b18f0126a0c74ee3bd5b4b0f4fec37e9cc7531

@4of92000 Thanks for reporting this here!

@eagleeyez Thanks for forking and working on this! I didn't use your exact solution, since the old lesson bar is still used for timed practice (at least for me). The new code should handle either bar just fine.

**Comment by 4of92000** [comment]
Thanks.
